stages:
  - build

image: node:8


build:
  stage: build
  tags: [docker]
  script:
    - npm i
    - npm run lint
    - npm run zip
  artifacts:
    expire_in: 1 day
    paths:
    - niobium-password-gen.zip
