#!/bin/bash

USER=robblue2x
PASS=`cat ~/.gitlabPAT`

docker login --username="${USER}" --password="${PASS}" registry.gitlab.com

docker build -t registry.gitlab.com/robblue2x/niobium-password-gen .

docker push registry.gitlab.com/robblue2x/niobium-password-gen
